var Mpp={debug:function(d){this.DEBUG=d},add:function(d,a){if(this.isFunction(a)){if(d=a(this))this[a]=d}else if(this.isPlainObject(a))this[d]=a},isFunction:function(d){return Object.prototype.toString.call(d)==="[object Function]"},isPlainObject:function(d){return d&&Object.prototype.toString.call(d)==="[object Object]"&&!d.nodeType&&!d.setInterval},log:function(d,a,b){if(this.DEBUG){if(b)d=b+": "+d;if(window.console!==undefined&&console.log)console[a&&console[a]?a:"log"](d)}},DOMAIN:function(){var d=
location.hostname;return d=d.indexOf("taobao.net")>0?"taobao.net":"taobao.com"}()};Mpp.add("Config",function(d){d.Config={notifyURL:function(){var a=location.hostname;a=a.indexOf("taobao.net")>0?"daily.taobao.net:8080":"taobao.com";return"http://mpp."+a+"/connection.html"}()}});
Mpp.add("JSON",function(d){function a(h){return h<10?"0"+h:h}function b(h){g.lastIndex=0;return g.test(h)?'"'+h.replace(g,function(k){var l=s[k];return typeof l==="string"?l:"\\u"+("0000"+k.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+h+'"'}function c(h,k){var l,n,q=f,m,i=k[h];if(i&&typeof i==="object"&&typeof i.toJSON==="function")i=i.toJSON(h);if(typeof r==="function")i=r.call(k,h,i);switch(typeof i){case "string":return b(i);case "number":return isFinite(i)?String(i):"null";case "boolean":case "null":return String(i);
case "object":if(!i)return"null";f+=o;m=[];if(Object.prototype.toString.apply(i)==="[object Array]"){n=i.length;for(h=0;h<n;h+=1)m[h]=c(h,i)||"null";k=m.length===0?"[]":f?"[\n"+f+m.join(",\n"+f)+"\n"+q+"]":"["+m.join(",")+"]";f=q;return k}if(r&&typeof r==="object"){n=r.length;for(h=0;h<n;h+=1){l=r[h];if(typeof l==="string")if(k=c(l,i))m.push(b(l)+(f?": ":":")+k)}}else for(l in i)if(Object.hasOwnProperty.call(i,l))if(k=c(l,i))m.push(b(l)+(f?": ":":")+k);k=m.length===0?"{}":f?"{\n"+f+m.join(",\n"+f)+
"\n"+q+"}":"{"+m.join(",")+"}";f=q;return k}}var e={};if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var j=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f,o,s={"":"\\b","\t":"\\t","\n":"\\n","":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},r;if(typeof e.stringify!=="function")e.stringify=function(h,k,l){var n;o=f="";if(typeof l==="number")for(n=0;n<l;n+=1)o+=" ";else if(typeof l==="string")o=l;if((r=k)&&typeof k!=="function"&&(typeof k!=="object"||typeof k.length!=="number"))throw new Error("JSON.stringify");return c("",{"":h})};
if(typeof e.parse!=="function")e.parse=function(h,k){function l(n,q){var m,i,p=n[q];if(p&&typeof p==="object")for(m in p)if(Object.hasOwnProperty.call(p,m)){i=l(p,m);if(i!==undefined)p[m]=i;else delete p[m]}return k.call(n,q,p)}h=String(h);j.lastIndex=0;if(j.test(h))h=h.replace(j,function(n){return"\\u"+("0000"+n.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(h.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){h=eval("("+h+")");return typeof k==="function"?l({"":h},""):h}throw new SyntaxError("JSON.parse");};d.JSON=e});
Mpp.add("Cookie",function(d){d.Cookie={get:function(a){var b;if(this.isNotEmptyString(a))if(a=document.cookie.match("(?:^| )"+a+"(?:(?:=([^;]*))|;|$)"))b=a[1]?decodeURIComponent(a[1]):"";return b},set:function(a,b,c,e,j,g){b=encodeURIComponent(b);var f=c;if(typeof f==="number"){f=new Date;f.setTime(f.getTime()+c*864E5)}if(f instanceof Date)b+="; expires="+f.toUTCString();if(this.isNotEmptyString(e))b+="; domain="+e;if(this.isNotEmptyString(j))b+="; path="+j;if(g)b+="; secure";document.cookie=a+"="+
b},remove:function(a){this.set(a,"",0)},isNotEmptyString:function(a){return typeof a==="string"&&a!==""}}});
Mpp.add("mpp-ua",function(d){var a=navigator.userAgent,b,c={webkit:0,chrome:0,safari:0,gecko:0,firefox:0,ie:0,opera:0,mobile:"",safe:0,sogo:0,tt:0,maxthon:0},e=function(j){var g=0;return parseFloat(j.replace(/\./g,function(){return g++===0?".":""}))};if((b=a.match(/AppleWebKit\/([\d.]*)/))&&b[1]){c.webkit=e(b[1]);if((b=a.match(/Chrome\/([\d.]*)/))&&b[1])c.chrome=e(b[1]);else if((b=a.match(/\/([\d.]*) Safari/))&&b[1])c.safari=e(b[1]);if(/ Mobile\//.test(a))c.mobile="Apple";else if(b=a.match(/NokiaN[^\/]*|Android \d\.\d|webOS\/\d\.\d/))c.mobile=
b[0]}else if((b=a.match(/Opera\/.* Version\/([\d.]*)/))&&b[1]){c.opera=e(b[1]);if(a.match(/Opera Mini[^;]*/))c.mobile=b[0]}else if((b=a.match(/MSIE\s([^;]*)/))&&b[1]){c.ie=e(b[1]);if(b=a.match(/360SE/))c.safe="360SE";if((b=a.match(/SE\s([^;]*)/))&&b[1])c.sogo=e(b[1]);if((b=a.match(/TencentTraveler\s([^;]*)/))&&b[1])c.tt=e(b[1]);if(window.external&&window.external.max_version)c.maxthon=e(window.external.max_version).toFixed(1)}else if(b=a.match(/Gecko/)){c.gecko=1;if((b=a.match(/rv:([\d.]*)/))&&b[1])c.gecko=
e(b[1]);if((b=a.match(/Firefox\/([\d.]*)/))&&b[1])c.firefox=e(b[1])}d.UA=c});
Mpp.add("Data",function(d){var a=d.Cookie,b=0;d.Data={CREATE_CONNECTION_STATUS:-1,NOTIFY_STATUS:{LOGOUT:0,TIMEOUT:1,MESSAGE:2,CLOSED:3},init:function(){a.set("mpp","t=1&m=&h=&l="+(new Date).getTime(),null,d.DOMAIN,"/")},setData:function(c){var e="";e="t="+c.t+"&m="+(c.m||"")+"&h="+(c.h||0)+"&l="+(c.l||0);a.set("mpp",e,null,d.DOMAIN,"/")},getData:function(){var c=a.get("mpp"),e={get:this.__get};if(c){c=c.split("&");for(var j=0;j<c.length;j++){var g=c[j].split("=");e[g[0]]=g[1]}}return e},setHeart:function(c){var e=
"";e=this.getData();e="t="+e.t+"&m="+e.m+"&h="+c+"&l="+e.l;a.set("mpp",e,null,d.DOMAIN,"/")},isCreatingConnection:function(c){return c==-1},clear:function(){a.set("mpp","t=0&m=&h=0&l=0",null,d.DOMAIN,"/")},getUserNick:function(){var c=a.get("_nk_")||"";return unescape(c.replace(/\\u/g,"%u"))},setLocalHeart:function(){var c=this.getData();c.l=b=(new Date).getTime();this.setData(c)},isNotNewFocused:function(){var c=this.getData();return b==c.l},__get:function(){if(this.__m)return this.__m;else{var c=
[],e;if(this.m){e=this.m.split("$");for(var j=0;j<e.length;j++){var g=e[j].split("#");c.push({g:parseInt(g[0]),t1:parseInt(g[1]),t2:parseInt(g[2])})}this.__m=c}return c}}}});Mpp.add("Notify",function(d){var a={};d.Notify={register:function(b){a[b.appId]||(a[b.appId]={});a[b.appId][b.type]||(a[b.appId][b.type]=[]);a[b.appId][b.type].push(b.callback)},__call:function(b,c){if(a[b]&&a[b][c])for(var e=0;e<a[b][c].length;e++)setTimeout(a[b][c][e],1)}}});
Mpp.add("Heart",function(d){var a=d.Data,b=d.Config,c=false,e=null,j=0;d.Heart={start:function(){c=true;this.__checkHeart();d.log("\u767b\u5f55\u5b8c\u6210\uff0c\u5f00\u59cb\u957f\u8fde\u63a5.")},restart:function(){c=true;this.__checkHeart()},stop:function(){if(c){d.log("\u505c\u6b62\u5916\u90e8\u957f\u94fe\u63a5\u68c0\u67e5\u3002");this.heartTimeoutTimer&&clearTimeout(this.heartTimeoutTimer);c=false}},__createConnection:function(){try{a.setHeart(a.CREATE_CONNECTION_STATUS);e=document.createElement("iframe");e.width=0;e.height=0;e.style.display="none";e.src=b.notifyURL;var g=document.getElementsByTagName("body")[0];
g.appendChild(e,g.lastChild)}catch(f){d.log("\u8fdc\u7a0b\u8fde\u63a5\u5f02\u5e38\u4e86\u2026\u2026"+f)}},__checkHeart:function(){var g=this;g.heartTimeoutTimer&&clearTimeout(g.heartTimeoutTimer);if(c)g.heartTimeoutTimer=setTimeout(function(){var f=a.getData();d.log("\u68c0\u67e5\u957f\u94fe\u63a5\uff0c\u91cd\u65b0\u5f00\u59cb:"+((new Date).getTime()-f>6E3)+","+((new Date).getTime()-f.h)+","+(new Date).getTime()+","+f.h);if(f.h==a.CREATE_CONNECTION_STATUS||(new Date).getTime()-f.h>6E3&&f.h!==a.CREATE_CONNECTION_STATUS&&f.t!==a.NOTIFY_STATUS.LOGOUT){if(e){d.log("\u957f\u94fe\u63a5\u7684frame\u5df2\u7ecf\u5b58\u5728\u3002");e.src=b.notifyURL}else{g.__createConnection();
d.log("\u957f\u94fe\u63a5\u7684frame\u4e0d\u5df2\u7ecf\u5b58\u5728\u3002")}f.h=(new Date).getTime();a.setData(f);c=true;g.__checkConnection()}g.__checkHeart()},6E3)},__checkConnection:function(){var g=this;j++<4&&setTimeout(function(){if(a.isCreatingConnection(a.getData().h))if(e){d.log("\u957f\u94fe\u63a5\u7684frame\u5df2\u7ecf\u5b58\u5728\u3002");e.src=b.NOTIFY_STATUS}else{g.__createConnection();d.log("\u957f\u94fe\u63a5\u7684frame\u4e0d\u5df2\u7ecf\u5b58\u5728\u3002")}},1E4)}}});
Mpp.add("Control",function(d){var a=d.Data,b=d.Heart,c=d.Notify,e=false,j=false;d.Control={init:function(){this.__bindEvent()},start:function(){if(this.__isLogin()){a.init();j=true;b.start();this.fire()}else a.clear()},restart:function(){j=true;this.fire()},stop:function(){j=false;this.eventTimer&&clearTimeout(this.eventTimer);b.stop();a.clear()},fire:function(){var g=this;g.eventTimer&&clearTimeout(g.eventTimer);g.eventTimer=setTimeout(function(){if(j&&(e||a.isNotNewFocused())){var f=a.getData(),
o=parseInt(f.t),s=f.get();f.m="";f.t=a.NOTIFY_STATUS.TIMEOUT;a.setData(f);d.log("local get data:"+o);switch(o){case a.NOTIFY_STATUS.LOGOUT:g.stop();a.clear();break;case a.NOTIFY_STATUS.MESSAGE:for(f=0;f<s.length;f++)c.__call(s[f].t1,s[f].t2);g.fire();break;default:g.fire()}}},1E3)},__bindEvent:function(){var g=this,f=function(){d.log("\u5f53\u524d\u7a97\u53e3\u83b7\u5f97\u7126\u70b9");e=true;if(g.__isLogin()){if(a.getData().t==a.NOTIFY_STATUS.LOGOUT)a.init();else a.isNotNewFocused()||a.setLocalHeart();g.restart();b.restart()}},o=function(){d.log("\u5f53\u524d\u7a97\u53e3\u5931\u53bb\u7126\u70b9\u3002");
e=false};if(d.UA.ie){window.onfocus=f;window.onblur=o}else{addEventListener("focus",f,false);addEventListener("blur",o,false)}},__isLogin:function(){return!!a.getUserNick()}}});Mpp.add("Load",function(d){d.Load={init:function(){d.Control.init();d.Control.start()}}});try{setTimeout(function(){Mpp.Load.init()},100)}catch(e$$1){Mpp.log("load error.")};
